import { IConfigField } from "shared/ui/input";
import {
  carBody,
  damageClassification,
  typeDrive,
  typeEngine,
  typePassportPTS,
  typeTransmission,
} from "../selectors/selectors";

export const characteristicFormConfig: IConfigField[] = [
  {
    type: "dropdwn",
    isValid: true,
    key: "car_body",
    placeholder: "Кузов",
    optionLabel: "title",
    optionValue: "value",
    options: carBody,
    indexForm: 3,
  },
  {
    type: "color",
    isValid: false,
    key: "car_color",
    placeholder: "Цвет",
    indexForm: 3,
  },
  {
    type: "number",
    isValid: false,
    key: "mileage",
    placeholder: "Пробег, км",
    indexForm: 3,
  },
  {
    type: "dropdwn",
    isValid: false,
    key: "car_damage",
    placeholder: "Классификация повреждений",
    optionLabel: "title",
    optionValue: "value",
    options: damageClassification,
    indexForm: 3,
  },
  {
    type: "dropdwn",
    isValid: false,
    key: "passport_pts",
    placeholder: "Паспорт (ПТС)",
    optionLabel: "title",
    optionValue: "value",
    options: typePassportPTS,
    indexForm: 3,
  },
  {
    type: "checkbox",
    isValid: false,
    key: "isNotFreeField",
    placeholder: "Отметка о прекращении регистрации на основании п.60.10 Административного регламента ГИБДД",
    indexForm: 3,
  },
  {
    type: "checkbox",
    isValid: false,
    key: "isMarkTermitionRegistrationCar",
    placeholder: "Нет свободных полей",
    indexForm: 3,
  },
  {
    type: "checkbox",
    isValid: false,
    key: "isMarkMVD",
    placeholder: "Отметки МВД о прохождении криминалистической экспертизы",
    indexForm: 3,
  },
  {
    type: "dropdwn",
    isValid: false,
    key: "type_engine",
    placeholder: "Тип двигателя",
    optionLabel: "title",
    optionValue: "value",
    options: typeEngine,
    indexForm: 3,
  },
  {
    type: "number",
    isValid: false,
    key: "volume_engine",
    placeholder: "Объем двигателя",
    indexForm: 3,
  },
  {
    type: "number",
    isValid: false,
    key: "power_engine",
    placeholder: "Мощность двигателя",
    indexForm: 3,
  },
  {
    type: "dropdwn",
    isValid: false,
    key: "engine_damage",
    placeholder: "Повреждения двигателя",
    optionLabel: "title",
    optionValue: "value",
    options: damageClassification,
    indexForm: 3,
  },
  {
    type: "dropdwn",
    isValid: false,
    key: "type_drive",
    placeholder: "Привод",
    optionLabel: "title",
    optionValue: "value",
    options: typeDrive,
    indexForm: 3,
  },
  {
    type: "dropdwn",
    isValid: false,
    key: "type_transmission",
    placeholder: "Коробка передач",
    optionLabel: "title",
    optionValue: "value",
    options: typeTransmission,
    indexForm: 3,
  },
  {
    type: "dropdwn",
    isValid: false,
    key: "KPP_damage",
    placeholder: "Повреждение КПП",
    optionLabel: "title",
    optionValue: "value",
    options: damageClassification,
    indexForm: 3,
  },
  {
    type: "checkbox",
    isValid: false,
    key: "isWithdrawalAccountingGBDD",
    placeholder: "Возможно наличие справки о снятии ТС с учета ГИБДД и передачи ПТС в ГИБДД",
    indexForm: 3,
  },
  {
    type: "checkbox",
    isValid: false,
    key: "isHidingMechanicDamage",
    placeholder: "Возможны скрытые механические повреждения",
    indexForm: 3,
  },
  {
    type: "checkbox",
    isValid: false,
    key: "isFullEquipment",
    placeholder: "ТС (ГОТС) передается согласно штатной комплектации",
    indexForm: 3,
  },
  {
    type: "checkbox",
    isValid: false,
    key: "isGOTSParkingLotSK",
    placeholder: "ГОТС на стоянке СК",
    indexForm: 3,
  },
  {
    type: "textarea",
    isValid: false,
    key: "comment",
    placeholder: "Комментарий",
    indexForm: 3,
  },
];
