import { IConfigField } from "shared/ui/input";
import { insurances, objectsAuction, offerPeriods, typeAuction } from "shared/config/selectors";

export const lotFormConfig: IConfigField[] = [
  {
    type: "dropdwn",
    isValid: true,
    key: "object_auction",
    placeholder: "Объект торгов*",
    optionLabel: "title",
    optionValue: "value",
    options: objectsAuction,
    indexForm: 1,
  },
  {
    type: "dropdwn",
    isValid: true,
    key: "type_insurance",
    placeholder: "Вид страхования*",
    optionLabel: "title",
    optionValue: "value",
    options: insurances,
    indexForm: 1,
  },
  {
    type: "dropdwn",
    isValid: true,
    key: "isOpen",
    placeholder: "Тип аукциона*",
    optionLabel: "title",
    optionValue: "value",
    options: typeAuction,
    indexForm: 1,
  },
  {
    type: "date",
    isValid: true,
    key: "date_start",
    placeholder: "Начало торгов*",
    min: new Date(),
    indexForm: 1,
  },
  {
    type: "date",
    isValid: true,
    key: "date_deadline",
    placeholder: "Окончание торгов*",
    min: new Date(),
    indexForm: 1,
  },
  {
    type: "other",
    nameSlot: "timeViewer",
  },
  {
    type: "dropdwn",
    isValid: true,
    key: "offer_period",
    placeholder: "Срок обязывающего предложения*",
    optionLabel: "title",
    optionValue: "value",
    options: offerPeriods,
    indexForm: 1,
  },
  {
    type: "mask",
    isValid: true,
    key: "case_number",
    placeholder: "Номер дела*",
    mask: "999-999-99",
    indexForm: 1,
  },
  {
    type: "dropdwn",
    isValid: true,
    key: "region",
    placeholder: "Регион*",
    optionLabel: "name",
    options: [],
    indexForm: 1,
  },
  {
    type: "dropdwn",
    isValid: true,
    key: "city",
    placeholder: "Город*",
    optionLabel: "name",
    options: [],
    indexForm: 1,
  },
];
