import { insurances, offerPeriods, typeCar } from "shared/config/selectors";
import { enumTypeUI, IConfigField } from "shared/ui/input";

export const configForm: IConfigField[] = [
  {
    type: "dropdwn",
    key: "type_insurance",
    placeholder: "Вид страхования",
    optionLabel: "title",
    optionValue: "value",
    options: insurances,
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "number",
    key: "type_insurance",
    placeholder: "VIN/Frame",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "type_insurance",
    placeholder: "№ Дела",
    optionLabel: "title",
    optionValue: "value",
    options: offerPeriods,
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "number",
    key: "type_insurance",
    placeholder: "Год",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "date",
    key: "date_start",
    placeholder: "Дата добавления",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "date",
    key: "date_start",
    placeholder: "Дата завершения",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "car_type",
    placeholder: "Тип авто",
    optionLabel: "title",
    optionValue: "value",
    isValid: false,
    options: typeCar,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "car_brand",
    placeholder: "Марка авто",
    optionLabel: "brand",
    isValid: false,
    options: [],
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "car_model",
    placeholder: "Модель*",
    optionLabel: "model",
    options: [],
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
];
