import { insurances, offerPeriods, typeCar } from "shared/config/selectors";
import { enumTypeUI, IConfigField } from "shared/ui/input";

export const configForm: IConfigField[] = [
  {
    type: "dropdwn",
    key: "type_insurance_like",
    placeholder: "Вид страхования",
    optionLabel: "title",
    optionValue: "value",
    options: insurances,
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "number",
    key: "VIN_number_like",
    placeholder: "VIN",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "number",
    key: "frame_number_like",
    placeholder: "Frame",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "offer_period_like",
    placeholder: "№ Дела",
    optionLabel: "title",
    optionValue: "value",
    options: offerPeriods,
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "number",
    key: "release_year_like",
    placeholder: "Год",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "date",
    key: "date_start_like",
    placeholder: "Дата добавления",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "date",
    key: "date_deadline_like",
    placeholder: "Дата завершения",
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "car_type_like",
    placeholder: "Тип авто",
    optionLabel: "title",
    optionValue: "value",
    isValid: false,
    options: typeCar,
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "car_brand.brand_like",
    placeholder: "Марка авто",
    optionLabel: "brand",
    isValid: false,
    options: [],
    typeUI: enumTypeUI.BASE,
  },
  {
    type: "dropdwn",
    key: "car_model.model_like",
    placeholder: "Модель",
    optionLabel: "model",
    options: [],
    isValid: false,
    typeUI: enumTypeUI.BASE,
  },
];
